### ISSUE TITLE
couldn't find "libQPlayer.so

### ISSUE THREAD

**Issue by ceylog** [lishuhao/flutter_video_player#4]
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider
enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                       0.9s
Resolving dependencies...                                    1.9s
Gradle task 'assembleDebug'...
Gradle task 'assembleDebug'... Done                          7.2s
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                  2.0s
Syncing files to device Android SDK built for x86...
I/System.out( 7827): {videoPath=http://qn.isanye.cn/%E5%A5%87%E8%BF%B9%E7%9A%84%E5%B1%B1.mp4, isLiveStreaming=false}
D/        ( 7827): HostConnection::get() New Host Connection established 0xe2f20680, tid 7844
D/        ( 7827): HostConnection::get() New Host Connection established 0xe2f20480, tid 7840
W/AudioManager( 7827): Use of stream types is deprecated for operations other than volume control
W/AudioManager( 7827): See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
W/System.err( 7827): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file"/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.example.mylive-5CL5w7BZw9NOomYTHQE09g==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.mylive-5CL5w7BZw9NOomYTHQE09g==/lib/x86, /data/app/com.example.mylive-5CL5w7BZw9NOomYTHQE09g==/base.apk!/lib/x86, /system/lib]]] couldn't find "libQPlayer.so"
W/System.err( 7827):    at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
W/System.err( 7827):    at java.lang.System.loadLibrary(System.java:1669)
W/System.err( 7827):    at com.qiniu.qplayer.mediaEngine.MediaPlayer.<clinit>(MediaPlayer.java:122)
W/System.err( 7827):    at com.pili.pldroid.player.PLMediaPlayer.<init>(PLMediaPlayer.java:47)
W/System.err( 7827):    at com.pili.pldroid.player.widget.a.a(PLBaseVideoView.java:594)
W/System.err( 7827):    at com.pili.pldroid.player.widget.a$3.a(PLBaseVideoView.java:1209)
W/System.err( 7827):    at com.pili.pldroid.player.widget.PLVideoView$a$1.surfaceCreated(PLVideoView.java:140)
W/System.err( 7827):    at android.view.SurfaceView.updateSurface(SurfaceView.java:670)
W/System.err( 7827):    at android.view.SurfaceView$2.onPreDraw(SurfaceView.java:143)
W/System.err( 7827):    at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
W/System.err( 7827):    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2474)
W/System.err( 7827):    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
W/System.err( 7827):    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
W/System.err( 7827):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
W/System.err( 7827):    at android.view.Choreographer.doCallbacks(Choreographer.java:761)
W/System.err( 7827):    at android.view.Choreographer.doFrame(Choreographer.java:696)
W/System.err( 7827):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
W/System.err( 7827):    at android.os.Handler.handleCallback(Handler.java:873)
W/System.err( 7827):    at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err( 7827):    at android.os.Looper.loop(Looper.java:193)
W/System.err( 7827):    at android.app.ActivityThread.main(ActivityThread.java:6669)
W/System.err( 7827):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 7827):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
W/System.err( 7827):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
D/EGL_emulation( 7827): eglMakeCurrent: 0xe04176c0: ver 3 0 (tinfo 0xe104dc40)
D/        ( 7827): HostConnection::get() New Host Connection established 0xe2f20900, tid 7849
D/EGL_emulation( 7827): eglMakeCurrent: 0xe04172a0: ver 3 0 (tinfo 0xe2f03310)
D/EGL_emulation( 7827): eglMakeCurrent: 0xe04176c0: ver 3 0 (tinfo 0xe104dc40)
 2.3s

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on Android SDK built for x86 is available at:
http://127.0.0.1:51623/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
I/flutter ( 7827): null
I/flutter ( 7827): null
I/flutter ( 7827): null
I/flutter ( 7827): null
I/flutter ( 7827): null
I/flutter ( 7827): null
I/flutter ( 7827): null
I/flutter ( 7827): null
E/BufferQueueProducer( 7827): [SurfaceTexture-0-7827-0] cancelBuffer: BufferQueue has been abandoned
D/EGL_emulation( 7827): eglMakeCurrent: 0xe04176c0: ver 3 0 (tinfo 0xe104dc40)
E/Surface ( 7827): queueBuffer: error queuing buffer to SurfaceTexture, -19
E/EGL_emulation( 7827): tid 7856: swapBuffers(552): error 0x300d (EGL_BAD_SURFACE)
W/OpenGLRenderer( 7827): swapBuffers encountered EGL error 12301 on 0xe0418620, halting rendering...
D/EGL_emulation( 7827): eglMakeCurrent: 0xe04176c0: ver 3 0 (tinfo 0xe104dc40)
I/System.out( 7827): {videoPath=http://qn.isanye.cn/%E5%A5%87%E8%BF%B9%E7%9A%84%E5%B1%B1.mp4, isLiveStreaming=false}
W/AudioManager( 7827): Use of stream types is deprecated for operations other than volume control
W/AudioManager( 7827): See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
I/.example.myliv( 7827): Rejecting re-init on previously-failed class java.lang.Class<com.qiniu.qplayer.mediaEngine.MediaPlayer>: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.example.mylive-5CL5w7BZw9NOomYTHQE09g==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.mylive-5CL5w7BZw9NOomYTHQE09g==/lib/x86, /data/app/com.example.mylive-5CL5w7BZw9NOomYTHQE09g==/base.apk!/lib/x86, /system/lib]]] couldn't find "libQPlayer.so"
I/.example.myliv( 7827): (Throwable with no stack trace)
I/.example.myliv( 7827):
D/AndroidRuntime( 7827): Shutting down VM
E/AndroidRuntime( 7827): FATAL EXCEPTION: main
E/AndroidRuntime( 7827): Process: com.example.mylive, PID: 7827
E/AndroidRuntime( 7827): java.lang.NoClassDefFoundError: com.qiniu.qplayer.mediaEngine.MediaPlayer
E/AndroidRuntime( 7827):        at com.pili.pldroid.player.PLMediaPlayer.<init>(PLMediaPlayer.java:47)
E/AndroidRuntime( 7827):        at com.pili.pldroid.player.widget.a.a(PLBaseVideoView.java:594)
E/AndroidRuntime( 7827):        at com.pili.pldroid.player.widget.a$3.a(PLBaseVideoView.java:1209)
E/AndroidRuntime( 7827):        at com.pili.pldroid.player.widget.PLVideoView$a$1.surfaceCreated(PLVideoView.java:140)
E/AndroidRuntime( 7827):        at android.view.SurfaceView.updateSurface(SurfaceView.java:670)
E/AndroidRuntime( 7827):        at android.view.SurfaceView$2.onPreDraw(SurfaceView.java:143)
E/AndroidRuntime( 7827):        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
E/AndroidRuntime( 7827):        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2474)
E/AndroidRuntime( 7827):        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
E/AndroidRuntime( 7827):        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
E/AndroidRuntime( 7827):        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
E/AndroidRuntime( 7827):        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
E/AndroidRuntime( 7827):        at android.view.Choreographer.doFrame(Choreographer.java:696)
E/AndroidRuntime( 7827):        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
E/AndroidRuntime( 7827):        at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime( 7827):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 7827):        at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 7827):        at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime( 7827):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7827):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime( 7827):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime( 7827): Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.example.mylive-5CL5w7BZw9NOomYTHQE09g==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.mylive-5CL5w7BZw9NOomYTHQE09g==/lib/x86, /data/app/com.example.mylive-5CL5w7BZw9NOomYTHQE09g==/base.apk!/lib/x86, /system/lib]]] couldn't find "libQPlayer.so"
E/AndroidRuntime( 7827):        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
E/AndroidRuntime( 7827):        at java.lang.System.loadLibrary(System.java:1669)
E/AndroidRuntime( 7827):        at com.qiniu.qplayer.mediaEngine.MediaPlayer.<clinit>(MediaPlayer.java:122)
E/AndroidRuntime( 7827):        ... 21 more
I/Process ( 7827): Sending signal. PID: 7827 SIG: 9
Lost connection to device.

**Comment by OhYee** [comment]
Download the so file from https://github.com/pili-engineering/PLDroidPlayer/tree/master/releases
Then put them in `package:flutter_video_player/android/src/main/jniLibs/`
It will work.
